### ISSUE TITLE
Code missing for http://lemurian.herokuapp.com/

### ISSUE THREAD

**Issue by ianlcassidy** [thedataincubator/flask-framework#1]
Great demo!  But, it seems like several of the files are missing the code that was used to build the actual lemurian app.  Would it be possible to share the code in this repo?

**Comment by gotoariel** [comment]
This repo's meant to be a teaching tool - we think that the best way to learn the tools is to use them to build something. So putting the pieces together is left as an exercise to complete. However if you have specific questions I'm happy to answer.

**Comment by arnarejo** [comment]
Nice demo. would help if the code was shared. Thankz
