### ISSUE TITLE
Code does not compile in Heroku

### ISSUE THREAD

**Issue by alzulas** [thedataincubator/flask-framework#17]
I tried it without condo and it said that it didn't support that version of Python. Then I tried it with Conda and now I'm getting:

Preparing Python/Miniconda Environment
/tmp/codon/tmp/buildpacks/[censored possible key]/bin/steps/conda_compile: line 7: conda: command not found
!     Push rejected, failed to compile Python/Conda app.
!     Push failed

Still trouble shooting the issue, but this code base is definitely not for beginners, since it is broken.

**Comment by xofbd** [comment]
@alzulas 

According to [Heroku](https://devcenter.heroku.com/articles/python-support#supported-runtimes), they don't support Python 3.6.5. You can update `runtime.txt` to be a newer version of Python such as 3.8.5. That should work. Also, I tend to avoid Conda myself.

**Comment by alzulas** [comment]
I also avoid conda, but thought maybe it would help. Here's what I found out after trouble shooting. 
1. The version of python is too old, had to update runtime.txt to 3.9.2
2. The version of conda that is listed in the README is broken. Both the version from TDI and the version from the third party. 
3. Because we can't use conda, all packages listed in conda-requirements.txt need to be moved to requirements.txt

Once these things are fixed, it will run. The README and some of the files may need to be updated for future students.

**Comment by xofbd** [comment]
@alzulas Thanks, I was already working on a PR to makes these fixes.

**Comment by xofbd** [comment]
Addressed by PR #18
